version: '3'
services:
 
  app:
    container_name: app
    image: golang:1.21.6
    depends_on:
       - postgres
    environment:
      ENVIRONMENT: development
    volumes:
      - ./:/app/
    working_dir: /app
    expose:
      - 8080
    ports:
      - '8080:8080'
    command: >
      bash -c "go run ./cmd/main.go"
     
  postgres:
    container_name: postgres
    image: postgres:16.1-alpine3.19
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER:  user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - ./db_data:/var/lib/postgresql
    // Health Check  !!!!!
   
  migrate:
    image: migrate/migrate:v4.17.0
    volumes:
      - ./migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgres://user:password@postgres:5432/postgres?sslmode=disable",
        "up"
      ]
    depends_on:
       - postgres
// почитай что такое healthcheck и где и как правильно это делать
    healthcheck:
      test: pg_isready -U user -d postgres
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 60s
    