env: "local"  
http:
  httpport: 8080
postgres:
  dbname: "test"
  dbuser: "user"
  dbpassword: "user"
  dbhost: "localhost" #postgres localhost
  dbport: 5432
  dbsslmode: ""
addrage: "https://api.agify.io/?name="
addrgender: "https://api.genderize.io/?name="
addrnationality: "https://api.nationalize.io/?name="